services:
  fxql_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fxql_api_service
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    entrypoint: ['sh', './entrypoint.sh']
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: fxql_db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env